### PR TITLE
Feature/resolve issue 32

### PR DESCRIPTION
**Pull request by estenrye**
For some reason, in 14.3.37 it cannot resolve win_friendly_path from the windows cookbook.  This PR copies that functionality to the Helpers Library as a work around.

#32

### CODE REVIEW

**Comment by ivadim** [comment]
Hi @estenrye 
I tested this change today and it's good but I found a proper solution. Looks like I missed an include of "Windows::Helper" in resources\default.rb . Don't know why Chef didn't complain about this in earlier versions 😄 

Solution is here: https://github.com/chef-cookbooks/windows/pull/555/files

```
action_class do
  include Windows::Helper
  require 'json'
```

Could you please update your PR to use include ? 
Thank you in advance.

**Comment by estenrye** [comment]
@ivadim I can do that.

**Comment by estenrye** [comment]
@ivadim I have updated the PR as requested.

**Comment by ivadim** [comment]
@estenrye thank you for the contribution. 👍

**Pull request merged**
